/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projects */
        get: operations["get_projects_api_v1_projects__get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        /** Update Project */
        put: operations["update_project_api_v1_projects__project_id__put"];
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Tree
         * @description 获取项目的目录树结构
         */
        get: operations["get_project_tree_api_v1_projects__project_id__tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Folders
         * @description 获取指定项目下的所有文件夹
         */
        get: operations["get_folders_api_v1_folders__get"];
        put?: never;
        /**
         * Create Folder
         * @description 创建文件夹
         */
        post: operations["create_folder_api_v1_folders__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Folder
         * @description 更新文件夹基本信息
         */
        put: operations["update_folder_api_v1_folders__folder_id__put"];
        post?: never;
        /**
         * Delete Folder
         * @description 删除文件夹
         */
        delete: operations["delete_folder_api_v1_folders__folder_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/folders/{folder_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Move Folder
         * @description 移动文件夹或调整顺序
         *     - target_parent_id: 新的父级ID (移动操作)
         *     - new_order: 新的排序位置 (排序操作)
         */
        put: operations["move_folder_api_v1_folders__folder_id__move_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Notes
         * @description 获取章节列表，支持按文件夹或项目筛选
         */
        get: operations["get_notes_api_v1_notes__get"];
        put?: never;
        /**
         * Create Note
         * @description 创建章节
         */
        post: operations["create_note_api_v1_notes__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Note
         * @description 获取单个章节详情
         */
        get: operations["get_note_api_v1_notes__note_id__get"];
        /**
         * Update Note
         * @description 更新章节内容
         */
        put: operations["update_note_api_v1_notes__note_id__put"];
        post?: never;
        /**
         * Delete Note
         * @description 删除单个章节
         */
        delete: operations["delete_note_api_v1_notes__note_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch Delete Notes
         * @description 批量删除章节
         */
        post: operations["batch_delete_notes_api_v1_notes_batch_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{note_id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy Note
         * @description 复制章节
         */
        post: operations["copy_note_api_v1_notes__note_id__copy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notes/{note_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Move Note
         * @description 移动章节到新文件夹或调整顺序（排序）
         */
        put: operations["move_note_api_v1_notes__note_id__move_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Text
         * @description 生成文本（非流式）
         */
        post: operations["generate_text_api_v1_ai_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/generate/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Text Stream
         * @description 生成文本（流式）
         */
        post: operations["generate_text_stream_api_v1_ai_generate_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/segment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 文本分词分析
         * @description 对文本进行分词分析，返回词频统计结果
         *
         *     - **text**: 待分析的文本内容
         *     - **mode**: 分词模式 (default/full/search)
         *     - **top_k**: 返回高频词数量
         *     - **with_pos**: 是否返回词性标注
         */
        post: operations["segment_text_api_v1_analysis_segment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 文本统计信息
         * @description 获取文本的详细统计信息
         *
         *     - **text**: 待统计的文本内容
         *
         *     返回：字符数、词数、句子数、段落数、平均句长等指标
         */
        post: operations["text_statistics_api_v1_analysis_statistics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/keywords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 关键词提取
         * @description 使用 TF-IDF 算法从文本中提取关键词
         *
         *     - **text**: 待提取的文本内容
         *     - **top_k**: 提取关键词数量 (1-100)
         *     - **with_weight**: 是否返回权重
         */
        post: operations["extract_keywords_api_v1_analysis_keywords_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/similarity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 文本相似度比较
         * @description 比较两段文本的相似度
         *
         *     - **text1**: 文本1
         *     - **text2**: 文本2
         *
         *     返回：相似度分数 (0-1) 和共同词汇列表
         */
        post: operations["calculate_similarity_api_v1_analysis_similarity_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/segment/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 原始分词结果
         * @description 获取原始分词结果（不进行词频统计）
         *
         *     - **text**: 待分析的文本内容
         *     - **mode**: 分词模式
         *     - **with_pos**: 是否返回词性标注
         */
        post: operations["segment_text_raw_api_v1_analysis_segment_raw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIGenerateRequest */
        AIGenerateRequest: {
            /** Prompt */
            prompt: string;
            /** Model */
            model?: string | null;
            /** Context */
            context?: string | null;
            /**
             * Stream
             * @default false
             */
            stream: boolean;
            /**
             * Action
             * @default generate
             */
            action: string | null;
        };
        /** AIGenerateResponse */
        AIGenerateResponse: {
            /** Text */
            text: string;
        };
        /** ActNode */
        ActNode: {
            /**
             * Type
             * @default act
             * @constant
             */
            type: "act";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["NoteNode"][];
        };
        /** BatchDeleteRequest */
        BatchDeleteRequest: {
            /** Ids */
            ids: string[];
        };
        /** FolderCreate */
        FolderCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["FolderType"];
            /** Parent Id */
            parent_id?: string | null;
            /** Project Id */
            project_id: string;
            /**
             * Order
             * @default 0
             */
            order: number | null;
        };
        /** FolderResponse */
        FolderResponse: {
            /** Name */
            name: string;
            type: components["schemas"]["FolderType"];
            /** Parent Id */
            parent_id?: string | null;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Order */
            order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * FolderType
         * @enum {string}
         */
        FolderType: "volume" | "act";
        /** FolderUpdate */
        FolderUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KeywordExtractRequest
         * @description 关键词提取请求
         */
        KeywordExtractRequest: {
            /**
             * Text
             * @description 待提取的文本内容
             */
            text: string;
            /**
             * Top K
             * @description 提取关键词数量
             * @default 20
             */
            top_k: number;
            /**
             * With Weight
             * @description 是否返回权重
             * @default true
             */
            with_weight: boolean;
        };
        /**
         * KeywordExtractResponse
         * @description 关键词提取响应
         */
        KeywordExtractResponse: {
            /**
             * Keywords
             * @description 关键词列表
             */
            keywords: components["schemas"]["KeywordItem"][];
        };
        /**
         * KeywordItem
         * @description 关键词项
         */
        KeywordItem: {
            /**
             * Word
             * @description 关键词
             */
            word: string;
            /**
             * Weight
             * @description 权重
             */
            weight?: number | null;
        };
        /** MoveFolderRequest */
        MoveFolderRequest: {
            /** Target Parent Id */
            target_parent_id?: string | null;
            /** New Order */
            new_order: number;
        };
        /** MoveNoteRequest */
        MoveNoteRequest: {
            /** Target Folder Id */
            target_folder_id: string;
            /** New Order */
            new_order: number;
        };
        /** NoteCreate */
        NoteCreate: {
            /** Title */
            title: string;
            /**
             * Content
             * @default
             */
            content: string | null;
            /** Tags */
            tags?: string[] | null;
            /** @default draft */
            status: components["schemas"]["NoteStatus"] | null;
            /** Folder Id */
            folder_id: string;
            /** Project Id */
            project_id: string;
            /**
             * Order
             * @default 0
             */
            order: number | null;
        };
        /** NoteNode */
        NoteNode: {
            /**
             * Type
             * @default note
             * @constant
             */
            type: "note";
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Word Count
             * @default 0
             */
            word_count: number;
        };
        /** NoteResponse */
        NoteResponse: {
            /** Title */
            title: string;
            /**
             * Content
             * @default
             */
            content: string | null;
            /** Tags */
            tags?: string[] | null;
            /** @default draft */
            status: components["schemas"]["NoteStatus"] | null;
            /** Id */
            id: string;
            /** Folder Id */
            folder_id: string;
            /** Project Id */
            project_id: string;
            /** Order */
            order: number;
            /**
             * Word Count
             * @default 0
             */
            word_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Deleted At
             * Format: date-time
             * @description 软删除时间，null 表示未删除
             */
            deleted_at?: string | null;
        };
        /**
         * NoteStatus
         * @enum {string}
         */
        NoteStatus: "draft" | "revising" | "completed";
        /** NoteUpdate */
        NoteUpdate: {
            /** Title */
            title?: string | null;
            /** Content */
            content?: string | null;
            /** Folder Id */
            folder_id?: string | null;
            /** Tags */
            tags?: string[] | null;
            status?: components["schemas"]["NoteStatus"] | null;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Title */
            title: string;
            /** Genre */
            genre?: string[] | null;
            /** Description */
            description?: string | null;
            /** Cover */
            cover?: string | null;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Title */
            title: string;
            /** Genre */
            genre?: string[] | null;
            /** Description */
            description?: string | null;
            /** Cover */
            cover?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Title */
            title?: string | null;
            /** Genre */
            genre?: string[] | null;
            /** Description */
            description?: string | null;
            /** Cover */
            cover?: string | null;
        };
        /**
         * RawSegmentationResponse
         * @description 原始分词结果响应
         */
        RawSegmentationResponse: {
            /**
             * Segmented
             * @description 分词结果列表，每项包含词语和可选的词性标注
             */
            segmented: components["schemas"]["SegmentedWordItem"][];
        };
        /**
         * SegmentationMode
         * @description 分词模式
         * @enum {string}
         */
        SegmentationMode: "default" | "full" | "search";
        /**
         * SegmentationRequest
         * @description 分词分析请求
         */
        SegmentationRequest: {
            /**
             * Text
             * @description 待分析的文本内容
             */
            text: string;
            /** @default default */
            mode: components["schemas"]["SegmentationMode"];
            /**
             * Top K
             * @description 返回高频词数量
             * @default 50
             */
            top_k: number | null;
            /**
             * With Pos
             * @description 是否返回词性标注
             * @default false
             */
            with_pos: boolean;
        };
        /**
         * SegmentationResponse
         * @description 分词分析响应
         */
        SegmentationResponse: {
            /**
             * Total Words
             * @description 总词数（去重后）
             */
            total_words: number;
            /**
             * Total Tokens
             * @description 总词频（含重复）
             */
            total_tokens: number;
            /**
             * Words
             * @description 词语列表
             */
            words: components["schemas"]["WordItem"][];
            /**
             * Segmented Text
             * @description 分词后的文本序列
             */
            segmented_text: string[];
        };
        /**
         * SegmentedWordItem
         * @description 原始分词结果中的单个词语项
         */
        SegmentedWordItem: {
            /**
             * Word
             * @description 词语
             */
            word: string;
            /**
             * Pos
             * @description 词性标注（如果有）
             */
            pos?: string | null;
        };
        /**
         * TextSimilarityRequest
         * @description 文本相似度比较请求
         */
        TextSimilarityRequest: {
            /**
             * Text1
             * @description 文本1
             */
            text1: string;
            /**
             * Text2
             * @description 文本2
             */
            text2: string;
        };
        /**
         * TextSimilarityResponse
         * @description 文本相似度比较响应
         */
        TextSimilarityResponse: {
            /**
             * Similarity
             * @description 相似度（0-1之间）
             */
            similarity: number;
            /**
             * Common Words
             * @description 共同词汇
             */
            common_words: string[];
        };
        /**
         * TextStatisticsRequest
         * @description 文本统计请求
         */
        TextStatisticsRequest: {
            /**
             * Text
             * @description 待统计的文本内容
             */
            text: string;
        };
        /**
         * TextStatisticsResponse
         * @description 文本统计响应
         */
        TextStatisticsResponse: {
            /**
             * Char Count
             * @description 字符总数（含标点）
             */
            char_count: number;
            /**
             * Char Count No Spaces
             * @description 字符数（不含空格）
             */
            char_count_no_spaces: number;
            /**
             * Chinese Char Count
             * @description 中文字符数
             */
            chinese_char_count: number;
            /**
             * Word Count
             * @description 词数（按分词结果）
             */
            word_count: number;
            /**
             * Sentence Count
             * @description 句子数
             */
            sentence_count: number;
            /**
             * Paragraph Count
             * @description 段落数
             */
            paragraph_count: number;
            /**
             * Avg Sentence Length
             * @description 平均句长（词数）
             */
            avg_sentence_length: number;
            /**
             * Avg Word Length
             * @description 平均词长（字符数）
             */
            avg_word_length: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeNode */
        VolumeNode: {
            /**
             * Type
             * @default volume
             * @constant
             */
            type: "volume";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Order */
            order: number;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["ActNode"][];
        };
        /**
         * WordItem
         * @description 单个词语项
         */
        WordItem: {
            /**
             * Word
             * @description 词语
             */
            word: string;
            /**
             * Count
             * @description 出现次数
             */
            count: number;
            /**
             * Pos
             * @description 词性标注
             */
            pos?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_projects_api_v1_projects__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_api_v1_projects__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_v1_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_tree_api_v1_projects__project_id__tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeNode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_folders_api_v1_folders__get: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_folder_api_v1_folders__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_folder_api_v1_folders__folder_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_folder_api_v1_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_folder_api_v1_folders__folder_id__move_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folder_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_notes_api_v1_notes__get: {
        parameters: {
            query?: {
                folder_id?: string;
                project_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_note_api_v1_notes__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_note_api_v1_notes__note_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_note_api_v1_notes__note_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_v1_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_delete_notes_api_v1_notes_batch_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copy_note_api_v1_notes__note_id__copy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_note_api_v1_notes__note_id__move_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveNoteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_text_api_v1_ai_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_text_stream_api_v1_ai_generate_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_text_api_v1_analysis_segment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    text_statistics_api_v1_analysis_statistics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextStatisticsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextStatisticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_keywords_api_v1_analysis_keywords_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeywordExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeywordExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_similarity_api_v1_analysis_similarity_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextSimilarityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TextSimilarityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    segment_text_raw_api_v1_analysis_segment_raw_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RawSegmentationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
