"""initial tables

Revision ID: a72273cf3782
Revises: 
Create Date: 2026-03-11 15:50:54.626906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72273cf3782'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='小说名称'),
    sa.Column('genre', sa.JSON(), nullable=True, comment='题材'),
    sa.Column('description', sa.Text(), nullable=True, comment='简介'),
    sa.Column('cover', sa.String(length=500), nullable=True, comment='封面URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='卷名或幕名'),
    sa.Column('type', sa.Enum('volume', 'act', name='foldertype'), nullable=False, comment='类型'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父文件夹ID'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='所属项目ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_project_id'), 'folders', ['project_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='章节标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='章节内容'),
    sa.Column('folder_id', sa.String(length=36), nullable=False, comment='所属幕ID'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='所属项目ID'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序序号'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签'),
    sa.Column('word_count', sa.Integer(), nullable=True, comment='字数'),
    sa.Column('status', sa.Enum('draft', 'revising', 'completed', name='notestatus'), nullable=False, comment='状态'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_folder_id'), 'notes', ['folder_id'], unique=False)
    op.create_index(op.f('ix_notes_project_id'), 'notes', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_project_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_folder_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_folders_project_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_table('projects')
    # ### end Alembic commands ###
